services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data: