version: '3'
tasks:
  :build:
    cmds:
      - 'go build -o dist/main ./cmd/web/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  :start:
    cmds:
      - task: :build
      - './dist/main'
    sources:
      - ./*.go,
      - ./**/*.go
